import com.jkmcllc.aupair01.pairing.PairingRequest;
import com.jkmcllc.aupair01.pairing.PairingRequest.PairingRequestBuilder;
import com.jkmcllc.aupair01.structure.DeliverableType;
import com.jkmcllc.aupair01.structure.ExerciseStyle;
import com.jkmcllc.aupair01.structure.OptionType;
import com.jkmcllc.aupair01.structure.UnderlyerType;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 *
 * @author Jason Merecki
 */
public class PairingRequestBuilderApexDefault {
    
    public static PairingRequest buildCashNakedShortOptions() {
        PairingRequestBuilder builder = PairingRequest.newBuilder();
        
        // MSFT root used for this example
        builder.setDeliverableSymbol("MSFT").setDeliverableQty("100").setDeliverablePrice("60.40").setDeliverableType(DeliverableType.S).addDeliverable();
        builder.setOptionRootSymbol("MSFT").setOptionRootExerciseStyle(ExerciseStyle.A)
            .setOptionRootUnderlyerType(UnderlyerType.S).setOptionRootMultiplier("100.00").addOptionRoot();
        
        // cash secured put, prohibited short call
        builder.setPositionSymbol("MSFT  160115C00070000").setPositionOptionRoot("MSFT").setPositionQty(-5)
            .setPositionOptionType(OptionType.C).setPositionOptionStrike("70.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("1.01").addPosition();
        builder.setPositionSymbol("MSFT  160115P00070000").setPositionOptionRoot("MSFT").setPositionQty(-5)
            .setPositionOptionType(OptionType.P).setPositionOptionStrike("70.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("3.03").addPosition();
        
        
        // long options, unpaired
        builder.setPositionSymbol("MSFT  160115C00080000").setPositionOptionRoot("MSFT").setPositionQty(5)
            .setPositionOptionType(OptionType.C).setPositionOptionStrike("80.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("1.01").addPosition();
        builder.setPositionSymbol("MSFT  160115P00080000").setPositionOptionRoot("MSFT").setPositionQty(5)
            .setPositionOptionType(OptionType.P).setPositionOptionStrike("80.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("3.03").addPosition();
        
        builder.setAccountStrategyGroupName("apexCash");
        builder.addAccount("CashAcct1");

        
        PairingRequest pairingRequest = builder.build();
        return pairingRequest;
        
    }
    
    public static PairingRequest buildCashCoveredAndUnpairedStock() {
        PairingRequestBuilder builder = PairingRequest.newBuilder();
        
        // MSFT root 
        builder.setDeliverableSymbol("MSFT").setDeliverableQty("100").setDeliverablePrice("60.40").setDeliverableType(DeliverableType.S).addDeliverable();
        builder.setOptionRootSymbol("MSFT").setOptionRootExerciseStyle(ExerciseStyle.A)
            .setOptionRootUnderlyerType(UnderlyerType.S).setOptionRootMultiplier("100.00").addOptionRoot();
        
        // GPRO root
        builder.setDeliverableSymbol("GPRO").setDeliverableQty("100").setDeliverablePrice("46.00").setDeliverableType(DeliverableType.S).addDeliverable();
        builder.setOptionRootSymbol("GPRO").setOptionRootExerciseStyle(ExerciseStyle.A)
            .setOptionRootUnderlyerType(UnderlyerType.S).setOptionRootMultiplier("100.00").addOptionRoot();
        
        // long stock
        builder.setPositionSymbol("MSFT").setPositionQty(930).setPositionPrice("60.40").addPosition();
        
        // some short calls to make a covered call
        builder.setPositionSymbol("MSFT  160115C00070000").setPositionOptionRoot("MSFT").setPositionQty(-5)
            .setPositionOptionType(OptionType.C).setPositionOptionStrike("70.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("1.01").addPosition();

        // short stock (will have the 'prohibited' attribute set)
        builder.setPositionSymbol("GPRO").setPositionQty(-400).setPositionPrice("46.00").addPosition();
        
        builder.setAccountStrategyGroupName("apexCash");
        builder.addAccount("CashAcct1");

        PairingRequest pairingRequest = builder.build();
        return pairingRequest;
        
    }
    
    public static PairingRequest buildCashPutProtectives() {
        PairingRequestBuilder builder = PairingRequest.newBuilder();
        
        // GPRO root
        builder.setDeliverableSymbol("GPRO").setDeliverableQty("100").setDeliverablePrice("46.00").setDeliverableType(DeliverableType.S).addDeliverable();
        builder.setOptionRootSymbol("GPRO").setOptionRootExerciseStyle(ExerciseStyle.A)
            .setOptionRootUnderlyerType(UnderlyerType.S).setOptionRootMultiplier("100.00").addOptionRoot();
        
        builder.setPositionSymbol("GPRO  160115P00045000").setPositionOptionRoot("GPRO").setPositionQty(5)
            .setPositionOptionType(OptionType.P).setPositionOptionStrike("45.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("1.03").addPosition();

        // long stock 
        builder.setPositionSymbol("GPRO").setPositionQty(410).setPositionPrice("46.00").addPosition();
        
        builder.setAccountStrategyGroupName("apexCash");
        builder.addAccount("CashAcct1");

        PairingRequest pairingRequest = builder.build();
        return pairingRequest;
    }
    
    public static PairingRequest buildCashConversion() {
        PairingRequestBuilder builder = PairingRequest.newBuilder();
        
        // GPRO root
        builder.setDeliverableSymbol("GPRO").setDeliverableQty("100").setDeliverablePrice("46.00").setDeliverableType(DeliverableType.S).addDeliverable();
        builder.setOptionRootSymbol("GPRO").setOptionRootExerciseStyle(ExerciseStyle.A)
            .setOptionRootUnderlyerType(UnderlyerType.S).setOptionRootMultiplier("100.00").addOptionRoot();
        
        builder.setPositionSymbol("GPRO  160115P00045000").setPositionOptionRoot("GPRO").setPositionQty(5)
            .setPositionOptionType(OptionType.P).setPositionOptionStrike("45.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("1.03").addPosition();
        builder.setPositionSymbol("GPRO  160115C00045000").setPositionOptionRoot("GPRO").setPositionQty(-5)
            .setPositionOptionType(OptionType.C).setPositionOptionStrike("45.00").setPositionOptionExpiry("2016-01-15 16:00").setPositionPrice("1.03").addPosition();

        // long stock 
        builder.setPositionSymbol("GPRO").setPositionQty(610).setPositionPrice("46.00").addPosition();
        
        builder.setAccountStrategyGroupName("apexCash");
        builder.addAccount("CashAcct1");

        PairingRequest pairingRequest = builder.build();
        return pairingRequest;
    }


}
