import org.junit.Test;
import static org.junit.Assert.*;

import com.mereckiconsulting.aupair01.pairing.PairingRequest;
import com.mereckiconsulting.aupair01.pairing.PairingRequest.PairingRequestBuilder;
import com.mereckiconsulting.aupair01.structure.DeliverableType;
import com.mereckiconsulting.aupair01.structure.ExerciseStyle;
import com.mereckiconsulting.aupair01.structure.OptionType;
import com.mereckiconsulting.aupair01.structure.UnderlyerType;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 *
 * @author Jason Merecki, @date 8/9/16 4:59 PM
 */
public class PairingRequestBuilderTest {
    @Test public void build1() {
        PairingRequestBuilder builder = PairingRequest.newBuilder();
        
        // MSFT holdings, 3 call options symbols, 2 put option symbols
        builder.setLegSymbol("MSFT  160116C00047500").setLegOptionRoot("MSFT").setLegQty(6)
            .setLegOptionType(OptionType.C).setLegOptionStrike("47.50").setLegOptionExpiry("2016-01-16 16:00").addLeg();
        builder.setLegSymbol("MSFT  160116C00050000").setLegOptionRoot("MSFT").setLegQty(-8)
            .setLegOptionType(OptionType.C).setLegOptionStrike("50.00").setLegOptionExpiry("2016-01-16 16:00").addLeg();
        builder.setLegSymbol("MSFT  160116C00055000").setLegOptionRoot("MSFT").setLegQty(5)
            .setLegOptionType(OptionType.C).setLegOptionStrike("55.00").setLegOptionExpiry("2016-01-16 16:00").addLeg();
        
        // Build MSFT root, first deliverables then root information
        builder.setDeliverableSymbol("MSFT").setDeliverableQty("100").setDeliverableType(DeliverableType.S).addDeliverable();
        builder.setOptionRootSymbol("MSFT").setOptionRootExerciseStyle(ExerciseStyle.A).setOptionRootnderlyerType(UnderlyerType.S).addOptionRoot();
        
        
        PairingRequest pairingRequest = builder.build();
        System.out.println(pairingRequest);
        assertNotNull(pairingRequest);
    }
}
