import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Before;

import com.jkmcllc.aupair01.pairing.PairingRequest;
import com.jkmcllc.aupair01.pairing.PairingResponse;
import com.jkmcllc.aupair01.pairing.impl.PairingService;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 *
 * @author Jason Merecki, @date 8/9/16 4:59 PM
 */
public class PairingRequestTest {
   
    private PairingService pairingService = null;
    
    @Before
    public void setUp() {
        pairingService = PairingService.getInstance();
    }
    
    @Test
    public void build1AndPair() {
        PairingRequest pairingRequest = PairingRequestBuilderTest.buildRequest1();
        PairingResponse pairingResponse = pairingService.service(pairingRequest);
        assertNotNull(pairingResponse);
    }
    
}
