/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mereckifamilymac' at '8/22/16 9:54 PM' with Gradle 2.14
 *
 * @author mereckifamilymac, @date 8/22/16 9:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
