import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.jkmcllc.aupair01.pairing.AccountPairingResponse;
import com.jkmcllc.aupair01.pairing.PairingRequest;
import com.jkmcllc.aupair01.pairing.PairingResponse;
import com.jkmcllc.aupair01.pairing.strategy.Strategy;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * 
 * NOTE: the tests in this junit tests are intended to be executed only with custom configurations;
 * for example, assuming the files at this path exist, run with this java arg
 * -Dpairconfig=/opt/pair/pairconfig.ini,/opt/pair/apexdefault.ini
 *
 * @author Jason Merecki, @date 8/9/16 4:59 PM
 */
@Ignore
public class PairingRequestCustomConfigTest extends PairingRequestBase {
   
    @Test
    public void buildAndPairCustom() {
        PairingRequest pairingRequest = PairingRequestBuilderCustomConfig.buildCustomConfig();
        commonPrintInput(pairingRequest);
        PairingResponse pairingResponse = pairingService.service(pairingRequest);
        Map<String, AccountPairingResponse> responseByAccount = pairingResponse.getResultsByAccount();
        commonTestAndPrintOutput(pairingResponse, responseByAccount.size());
        
        
        boolean found = false;
        Map<String, List<Strategy>> singleAccountResult = null;

        singleAccountResult = responseByAccount.get("CashAcct1").getStrategies();

        found = findStrategy(singleAccountResult, "MSFT", "PutCashSecured", 5, new BigDecimal("35000"));
        assertTrue(found);
        
    }
    
}
