import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.jkmcllc.aupair01.pairing.AccountPairingResponse;
import com.jkmcllc.aupair01.pairing.PairingRequest;
import com.jkmcllc.aupair01.pairing.PairingResponse;
import com.jkmcllc.aupair01.pairing.strategy.Strategy;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * 
 * NOTE: the tests in this junit tests are intended to be executed only with custom configurations;
 * for example, assuming the files at this path exist, run with this java arg
 * -Dpairconfig=/opt/pair/pairconfig.ini,/opt/pair/apexdefault.ini
 *
 * @author Jason Merecki
 */
// @Ignore
public class PairingRequestTestApexDefault extends PairingRequestTestBase {
   
    @Test
    public void buildAndPairCustom1() {
        PairingRequest pairingRequest = PairingRequestBuilderApexDefault.buildCashNakedShortOptions();
        commonPrintInput(pairingRequest);
        PairingResponse pairingResponse = pairingService.service(pairingRequest);
        Map<String, AccountPairingResponse> responseByAccount = pairingResponse.getResultsByAccount();
        commonTestAndPrintOutput(pairingResponse, responseByAccount.size());
        
        boolean found = false;
        Map<String, List<Strategy>> singleAccountResult = null;
        singleAccountResult = responseByAccount.get("CashAcct1").getStrategies();

        found = findStrategy(singleAccountResult, "MSFT", "PutCashSecured", 5, new BigDecimal("35000"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "MSFT", "CallProhibitedShort", 5, new BigDecimal("3525.00"));
        assertTrue(found);
        
        found = findStrategy(singleAccountResult, "MSFT", "CallUnpairedLong", 5, new BigDecimal("0"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "MSFT", "PutUnpairedLong", 5, new BigDecimal("0"));
        assertTrue(found);
    }
    
    @Test
    public void buildAndPairCustom2() {
        PairingRequest pairingRequest = PairingRequestBuilderApexDefault.buildCashCoveredAndUnpairedStock();
        commonPrintInput(pairingRequest);
        PairingResponse pairingResponse = pairingService.service(pairingRequest);
        Map<String, AccountPairingResponse> responseByAccount = pairingResponse.getResultsByAccount();
        commonTestAndPrintOutput(pairingResponse, responseByAccount.size());
        
        boolean found = false;
        Map<String, List<Strategy>> singleAccountResult = null;
        singleAccountResult = responseByAccount.get("CashAcct1").getStrategies();

        found = findStrategy(singleAccountResult, "MSFT", "StockUnpairedLong", 430, new BigDecimal("0"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "MSFT", "CoveredCallCash", 5, new BigDecimal("0"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "GPRO", "StockProhibitedShort", 400, new BigDecimal("0"));
        assertTrue(found);
    }
    
    @Test
    public void buildAndPairCustom3() {
        PairingRequest pairingRequest = PairingRequestBuilderApexDefault.buildCashPutProtectives();
        commonPrintInput(pairingRequest);
        PairingResponse pairingResponse = pairingService.service(pairingRequest);
        Map<String, AccountPairingResponse> responseByAccount = pairingResponse.getResultsByAccount();
        commonTestAndPrintOutput(pairingResponse, responseByAccount.size());
        
        boolean found = false;
        Map<String, List<Strategy>> singleAccountResult = null;
        singleAccountResult = responseByAccount.get("CashAcct1").getStrategies();

        found = findStrategy(singleAccountResult, "GPRO", "ProtectivePutCash", 4, new BigDecimal("0"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "GPRO", "StockUnpairedLong", 10, new BigDecimal("0"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "GPRO", "PutUnpairedLong", 1, new BigDecimal("0"));
        assertTrue(found);
    }
    
    @Test
    public void buildAndPairCustom4() {
        PairingRequest pairingRequest = PairingRequestBuilderApexDefault.buildCashConversion();
        commonPrintInput(pairingRequest);
        PairingResponse pairingResponse = pairingService.service(pairingRequest);
        Map<String, AccountPairingResponse> responseByAccount = pairingResponse.getResultsByAccount();
        commonTestAndPrintOutput(pairingResponse, responseByAccount.size());
        
        boolean found = false;
        Map<String, List<Strategy>> singleAccountResult = null;
        singleAccountResult = responseByAccount.get("CashAcct1").getStrategies();

        found = findStrategy(singleAccountResult, "GPRO", "ConversionCash", 5, new BigDecimal("0"));
        assertTrue(found);
        found = findStrategy(singleAccountResult, "GPRO", "StockUnpairedLong", 110, new BigDecimal("0"));
        assertTrue(found);
    }
    
}
